In [1]:
import os
import pandas as pd
import glob
files = glob.glob('../data/*.csv')
print (files)


df = pd.concat([pd.read_csv(fp).assign(filename=os.path.basename(fp)) for fp in files])

['../data\\election_07-21-2020_10-40-22_3cands_0.006666666666666667noise.csv', '../data\\election_07-21-2020_10-40-23_3cands_0.02666666666666667noise.csv', '../data\\election_07-21-2020_10-40-23_3cands_0.03333333333333333noise.csv', '../data\\election_07-21-2020_10-40-23_3cands_0.03noise.csv', '../data\\election_07-21-2020_10-40-23_3cands_0.04666666666666667noise.csv', '../data\\election_07-21-2020_10-40-23_5cands_0.01noise.csv', '../data\\election_07-21-2020_10-40-23_5cands_0.026000000000000002noise.csv', '../data\\election_07-21-2020_10-40-24_3cands_0.013333333333333334noise.csv', '../data\\election_07-21-2020_10-40-24_3cands_0.016666666666666666noise.csv', '../data\\election_07-21-2020_10-40-24_3cands_0.023333333333333334noise.csv', '../data\\election_07-21-2020_10-40-24_3cands_0.043333333333333335noise.csv', '../data\\election_07-21-2020_10-40-24_4cands_0.0125noise.csv', '../data\\election_07-21-2020_10-40-24_4cands_0.0175noise.csv', '../data\\election_07-21-2020_10-40-24_6cands_0.0033333333333333335noise.csv', '../data\\election_07-21-2020_10-40-25_6cands_0.021666666666666667noise.csv', '../data\\election_07-21-2020_10-40-26_3cands_0.0033333333333333335noise.csv', '../data\\election_07-21-2020_10-40-26_3cands_0.03noise.csv', '../data\\election_07-21-2020_10-40-26_6cands_0.015noise.csv', '../data\\election_07-21-2020_10-40-27_4cands_0.0225noise.csv', '../data\\election_07-21-2020_10-40-27_4cands_0.0275noise.csv']

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 476977 entries, 0 to 34311
Data columns (total 10 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Unnamed: 0      476977 non-null  int64
 1   candidate_1     476977 non-null  object
 2   candidate_2     476977 non-null  object
 3   candidate_3     476977 non-null  object
 4   num_candidates  476977 non-null  int64
 5   noise           476977 non-null  float64
 6   filename        476977 non-null  object
 7   candidate_4     195866 non-null  object
 8   candidate_5     112849 non-null  object
 9   candidate_6     67378 non-null   object
dtypes: float64(1), int64(2), object(7)
memory usage: 27.3+ MB

In [3]:
df = df[['Unnamed: 0', 'candidate_1', 'candidate_2', 'candidate_3','candidate_4','candidate_5','candidate_6','noise', 'num_candidates', 'filename',]]

In [4]:
df.iloc[:, 1:-3]

,candidate_1,candidate_2,candidate_3,candidate_4,candidate_5,candidate_6
0,candidate_1,candidate_2,candidate_3,NaN,NaN,NaN
1,candidate_1,candidate_2,candidate_3,NaN,NaN,NaN
2,candidate_1,candidate_2,candidate_3,NaN,NaN,NaN
3,candidate_1,candidate_2,candidate_3,NaN,NaN,NaN
4,candidate_1,candidate_2,candidate_3,NaN,NaN,NaN
...,...,...,...,...,...,...
34307,candidate_4,candidate_3,candidate_2,candidate_1,NaN,NaN
34308,candidate_4,candidate_3,candidate_2,candidate_1,NaN,NaN
34309,candidate_4,candidate_3,candidate_2,candidate_1,NaN,NaN
34310,candidate_4,candidate_3,candidate_2,candidate_1,NaN,NaN
34311,candidate_4,candidate_3,candidate_2,candidate_1,NaN,NaN

In [5]:
df.shape

(476977, 10)

In [6]:
df.to_csv('master_election_new1.csv')

In [7]:
def create_master_file(file_name_pattern, master_file_path):
    file_names = [name for name in glob.glob(file_name_pattern)]
    # combine all files in the list
    data = []
    for csv in file_names:
#         print('csv:', csv)
        frame = pd.read_csv(csv)
#         print("before:", len(frame))        
        frame['filename'] = os.path.basename(csv)
        filter_col = [col for col in frame if col.startswith('candidate_')]
        for col in filter_col:
            idx = frame[col].str.isnumeric() & (frame[:][col] != '0')
            frame = frame[~idx]
#             print("after:", len(frame))
        data.append(frame)    # concat all dfs
    combined_csv_df = pd.concat(data)
    # export to csv
    combined_csv_df.to_csv(master_file_path, index=False)

In [8]:
# create_master_file(file_name_pattern, master_file_path)
file_name_pattern = "../data/*.csv"
master_file_path = "master_election_new.csv"
create_master_file(file_name_pattern, master_file_path)

In [10]:
sherin= pd.read_csv("master_election_new.csv")

c:\users\anxhe\appdata\local\programs\python\python38-32\lib\site-packages\IPython\core\interactiveshell.py:3062: DtypeWarning: Columns (7,8,9) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [11]:
anxhela = pd.read_csv('master_election_new1.csv')

c:\users\anxhe\appdata\local\programs\python\python38-32\lib\site-packages\IPython\core\interactiveshell.py:3062: DtypeWarning: Columns (5,6,7) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [12]:
pd.concat([anxhela,sherin]).drop_duplicates(keep=False)

,Unnamed: 0,Unnamed: 0.1,candidate_1,candidate_2,candidate_3,candidate_4,candidate_5,candidate_6,noise,num_candidates,filename
0,0,0.0,candidate_1,candidate_2,candidate_3,NaN,NaN,NaN,0.006667,3,election_07-21-2020_10-40-22_3cands_0.00666666...
1,1,1.0,candidate_1,candidate_2,candidate_3,NaN,NaN,NaN,0.006667,3,election_07-21-2020_10-40-22_3cands_0.00666666...
2,2,2.0,candidate_1,candidate_2,candidate_3,NaN,NaN,NaN,0.006667,3,election_07-21-2020_10-40-22_3cands_0.00666666...
3,3,3.0,candidate_1,candidate_2,candidate_3,NaN,NaN,NaN,0.006667,3,election_07-21-2020_10-40-22_3cands_0.00666666...
4,4,4.0,candidate_1,candidate_2,candidate_3,NaN,NaN,NaN,0.006667,3,election_07-21-2020_10-40-22_3cands_0.00666666...
...,...,...,...,...,...,...,...,...,...,...,...
476971,1406,NaN,candidate_4,candidate_3,candidate_2,candidate_1,NaN,NaN,0.027500,4,election_07-21-2020_10-40-27_4cands_0.0275nois...
476972,1407,NaN,candidate_4,candidate_3,candidate_2,candidate_1,NaN,NaN,0.027500,4,election_07-21-2020_10-40-27_4cands_0.0275nois...
476973,1408,NaN,candidate_4,candidate_3,candidate_2,candidate_1,NaN,NaN,0.027500,4,election_07-21-2020_10-40-27_4cands_0.0275nois...
476974,1409,NaN,candidate_4,candidate_3,candidate_2,candidate_1,NaN,NaN,0.027500,4,election_07-21-2020_10-40-27_4cands_0.0275nois...
476975,1410,NaN,candidate_4,candidate_3,candidate_2,candidate_1,NaN,NaN,0.027500,4,election_07-21-2020_10-40-27_4cands_0.0275nois...

In [13]:
anxhela.shape

(476977, 11)

In [30]:
sherin.shape

(476977, 9)

In [31]:
sherin.columns

Index(['Unnamed: 0', 'candidate_1', 'candidate_2', 'candidate_3',
       'num_candidates', 'noise', 'candidate_4', 'candidate_5', 'candidate_6'],
      dtype='object')

In [32]:
anxhela.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'candidate_1', 'candidate_2',
       'candidate_3', 'candidate_4', 'candidate_5', 'candidate_6', 'noise',
       'num_candidates', 'filename'],
      dtype='object')

In [ ]:
import pyrankvote
import ast
import pandas as pd
import numpy as np
from pyrankvote import Candidate, Ballot
import glob
import os

def create_master_file(file_name_pattern, master_file_path):
    file_names = [name for name in glob.glob(file_name_pattern)]
    # combine all files in the list
    data = []
    for csv in file_names:
#         print('csv:', csv)
        frame = pd.read_csv(csv)
#         print("before:", len(frame))        
        frame['filename'] = os.path.basename(csv)
        filter_col = [col for col in frame if col.startswith('candidate_')]
        for col in filter_col:
            idx = frame[col].str.isnumeric() & (frame[:][col] != '0')
            frame = frame[~idx]
#             print("after:", len(frame))
        data.append(frame)    # concat all dfs
    combined_csv_df = pd.concat(data)
    # export to csv
    combined_csv_df.to_csv(master_file_path, index=False)


def get_cand_list(df):
    list_of_unique_vals_in_dataframe = df.iloc[:, 1].value_counts().index
    cand_list = list(filter(lambda x: x.startswith('can'), list_of_unique_vals_in_dataframe))
    return cand_list

def initialize_cand_objs(cand_list):
    if isinstance(cand_list, str):
        return [Candidate(c) for c in cand_list.split(', ')]
    else:
        return [Candidate(c) for c in cand_list]

def initialize_cand_objs_in_df_cols(df):
    cands_df = df.iloc[:, 1:]  # getting all columns with candidate names in them
    cands_df = cands_df.applymap(lambda x: create_cand(x))  # making them into pyrankvote candidate objects
    cands_df['ballot_id'] = df.iloc[:, 0]  # stitching df back with ballot_ids from old dataframe
    return cands_df

def get_cands_into_single_cell(df):
    df['candidate_list'] = df.iloc[:,].agg(", ".join, axis=1) #this excludes the first candidates??
    return df

def initialize_ballot_objs(df):
    ballot_objects = []
    for index, value in enumerate(df['candidate_list']):
        ballot = Ballot(ranked_candidates=value)
        ballot_objects.append(ballot)
    return ballot_objects

def run_election(list_of_cand_objs, election_df):
    return pyrankvote.instant_runoff_voting(list_of_cand_objs, election_df['ballots'], pick_random_if_blank=True)

def rm_invalid_rows(df):
    return df[df['candidate_list'] != '0']


def main(df):
    
    election_dict = {}
    
    
    #renaming column to ballot_id
    df.rename(columns={'Unnamed: 0': 'ballot_id'}, inplace=True) # should be apart of the generating and concatenation script
    
    
    #getting  number of candidates:
    num_cands = df['num_candidates'].max()
    print("number of candidates in election:", num_cands)
    election_dict['num_candidates'] = num_cands

    #droping nans, 
    df = df.dropna(axis=1, how='all')
    df = df.drop(['ballot_id','filename'], axis=1)
    print('df.shape',df.shape)
        
    #aggregating all cand into one cell
    df = get_cands_into_single_cell(df)
    
    #Removing 0 with empty space:
    df['candidate_list'] = df['candidate_list'].apply(lambda x: x.replace('0, ', '').replace(', 0', ''))
    
    #Removing invalid rows:
    df = rm_invalid_rows(df)
    
    #for all srings making into pyrank candidate objects:
    df['candidate_list'] = df['candidate_list'].apply(lambda x: initialize_cand_objs(x))

    #creating ballot objects column for each candidate in candidate list:
    ballots = initialize_ballot_objs(df)
    df['ballots'] = ballots

    #getting unique list of candidates:
    cand_list = get_cand_list(df)
    cand_list = initialize_cand_objs(cand_list)
    print("cand_list: ",cand_list)
    
    #running pyrank election and getting winners:
    election = run_election(cand_list, df)
    winner = election.get_winners()
    
    #Dictionary keys and values *************************
    #printing winners and add dictionary key:
    
    print("get_winners",winner)
    election_dict['winner'] = winner
    
    # printing rounds and add dictionary key:
    print("rounds",len(election.rounds))
    election_dict['rounds'] = len(election.rounds)
    
    #print elections and add dictionary key:
    print("election:", election)
    election_dict['election'] = election

        
    #will return df and dictionary for us to read votes
    return df, election_dict